/**
 * pin-lock.js
 * Gatekeeper screen shown before the site is revealed.
 * PIN is set in /config/settings.js — do not edit this file.
 *
 * Deliberately has zero dependencies on config.js/OCEAN so it can never be
 * blocked by anything else failing to load — the lock always works.
 */
(function (window, document) {
  'use strict';

  // PIN comes from config/settings.js (loaded before this file in index.html).
  // The reveal screen shows the fixed code below; the code is 7 digits.
  var PIN_VALUE = '5201314';
  var PIN_LENGTH = PIN_VALUE.length;
  var STORAGE_KEY = 'oceanPinUnlocked';

  // Countdown target: September 6, 23:59 (one minute before midnight).
  var TARGET_DATE = new Date(new Date().getFullYear(), 8, 6, 23, 59, 0);
  var reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function ready(fn) {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', fn);
    } else {
      fn();
    }
  }

  // Saved pristine lock markup, captured on first init for re-lock.
  var savedLockHTML = null;
  var savedLockAnchor = null;

  function init() {
    var lock = document.getElementById('pinLock');
    if (!lock) {
      // No lock in the DOM — if we saved one earlier (relock case), rebuild it.
      if (savedLockHTML && savedLockAnchor) {
        savedLockAnchor.insertAdjacentHTML('afterbegin', savedLockHTML);
        lock = document.getElementById('pinLock');
      }
      if (!lock) return;
    }

    // Keep a pristine copy of the lock markup so we can re-show it on re-lock.
    if (!savedLockHTML) {
      savedLockHTML = lock.outerHTML;
      savedLockAnchor = lock.parentNode || document.body;
    }

    // Already unlocked earlier this session — skip straight to the site.
    try {
      if (window.sessionStorage && sessionStorage.getItem(STORAGE_KEY) === '1') {
        lock.parentNode && lock.parentNode.removeChild(lock);
        setTimeout(function() { window.dispatchEvent(new Event('pinUnlocked')); }, 500);
        return;
      }
    } catch (e) { /* sessionStorage unavailable — show the lock normally */ }

    setupLock(lock);
  }

  ready(init);

  function setupLock(lock) {
    if (!lock) return;
    var card       = lock.querySelector('.pin-lock__card');
    var countdown  = lock.querySelector('.pin-lock__countdown');
    var reveal     = lock.querySelector('.pin-lock__reveal');
    var timerEl    = lock.querySelector('.pin-lock__timer');
    var digitsWrap = lock.querySelector('.pin-lock__digits');
    var input      = lock.querySelector('.pin-lock__hidden-input');
    var errorEl    = lock.querySelector('.pin-lock__error');
    var form       = lock.querySelector('.pin-lock__form');

    if (!card || !countdown || !reveal || !timerEl || !digitsWrap || !input || !form) return;

    input.setAttribute('maxlength', String(PIN_LENGTH));

    // Build digit boxes dynamically from PIN_LENGTH
    var boxes = [];
    for (var i = 0; i < PIN_LENGTH; i++) {
      var box = document.createElement('span');
      box.className = 'pin-digit';
      var dot = document.createElement('span');
      dot.className = 'pin-digit__dot';
      box.appendChild(dot);
      digitsWrap.appendChild(box);
      boxes.push(box);
    }

    // ---- Countdown: gate the site until Sept 6 at 23:59, then reveal the code ----
    var timerCells = {
      days:  timerEl.querySelector('#pinTimerDays'),
      hours: timerEl.querySelector('#pinTimerHours'),
      mins:  timerEl.querySelector('#pinTimerMins'),
      secs:  timerEl.querySelector('#pinTimerSecs')
    };

    function pad(n) { return String(n).padStart(2, '0'); }

    function revealCode() {
      clearInterval(timerInterval);
      countdown.hidden = true;
      reveal.hidden = false;
      setTimeout(function () {
        try { input.focus({ preventScroll: true }); } catch (e) { input.focus(); }
      }, reducedMotion ? 0 : 350);
    }

    function tick() {
      var diff = TARGET_DATE.getTime() - Date.now();
      if (diff <= 0) {
        revealCode();
        return;
      }
      timerCells.days.textContent  = pad(Math.floor(diff / 86400000));
      timerCells.hours.textContent = pad(Math.floor(diff / 3600000) % 24);
      timerCells.mins.textContent  = pad(Math.floor(diff / 60000) % 60);
      timerCells.secs.textContent  = pad(Math.floor(diff / 1000) % 60);
    }

    var timerInterval = setInterval(tick, 1000);
    tick();

    setLocked(true);

    function setLocked(state) {
      document.documentElement.classList.toggle('pin-locked', state);
      var siblings = document.body.children;
      for (var s = 0; s < siblings.length; s++) {
        var el = siblings[s];
        if (el === lock) continue;
        if (state) {
          el.setAttribute('inert', '');
          el.setAttribute('aria-hidden', 'true');
        } else {
          el.removeAttribute('inert');
          el.removeAttribute('aria-hidden');
        }
      }
    }

    function render() {
      var val = input.value;
      boxes.forEach(function (box, idx) {
        box.classList.toggle('is-filled', idx < val.length);
        box.classList.toggle('is-active', idx === val.length);
      });
    }

    function clearError() {
      card.classList.remove('is-error');
      errorEl && errorEl.classList.remove('is-visible');
    }

    function shakeError() {
      clearError();
      input.value = '';
      render();
      void card.offsetWidth;
      card.classList.add('is-error');
      errorEl && errorEl.classList.add('is-visible');

      var onEnd = function () {
        card.classList.remove('is-error');
        card.removeEventListener('animationend', onEnd);
      };
      card.addEventListener('animationend', onEnd);

      setTimeout(function () {
        try { input.focus({ preventScroll: true }); } catch (e) { input.focus(); }
      }, reducedMotion ? 30 : 80);
    }

    function unlock() {
      input.blur();
      card.classList.add('is-success');
      try { sessionStorage.setItem(STORAGE_KEY, '1'); } catch (e) {}

      window.dispatchEvent(new Event('pinUnlocked'));

      var revealDelay = reducedMotion ? 150 : 850;
      setTimeout(function () {
        lock.classList.add('is-unlocked');
        setLocked(false);
        setTimeout(function () {
          if (lock.parentNode) lock.parentNode.removeChild(lock);
        }, reducedMotion ? 0 : 850);
      }, revealDelay);
    }

    function attemptUnlock() {
      var val = input.value.replace(/\D/g, '');
      if (val.length !== PIN_LENGTH || val !== PIN_VALUE) {
        shakeError();
        return;
      }
      unlock();
    }

    input.addEventListener('input', function () {
      input.value = input.value.replace(/\D/g, '').slice(0, PIN_LENGTH);
      clearError();
      render();
      if (input.value.length === PIN_LENGTH) attemptUnlock();
    });

    form.addEventListener('submit', function (e) {
      e.preventDefault();
      attemptUnlock();
    });

    lock.addEventListener('pointerdown', function (e) {
      if (!card.contains(e.target) || e.target === card) {
        input.focus({ preventScroll: true });
      }
    });

    render();
    setTimeout(function () {
      try { input.focus({ preventScroll: true }); } catch (e) {}
    }, reducedMotion ? 0 : 450);
  }

  // ---- Re-lock: bring the lock screen back on demand ----
  function relock() {
    // Clear the "unlocked this session" flag so the lock actually shows.
    try { sessionStorage.removeItem(STORAGE_KEY); } catch (e) {}
    window.dispatchEvent(new Event('relock'));

    // Remove the current lock (if mid-unlock/fading) so init rebuilds a fresh one.
    var existing = document.getElementById('pinLock');
    if (existing && existing.parentNode) {
      existing.parentNode.removeChild(existing);
    }

    // Pause the music player so it doesn't play behind the lock.
    document.querySelectorAll('.music-player').forEach(function (p) {
      var toggle = p.querySelector('.music-player__toggle');
      if (toggle && p.classList.contains('is-playing')) toggle.click();
    });

    // Re-run the lock init: it re-inserts the saved markup and re-shows the lock.
    // The countdown target is fixed (Sept 6 23:59), so remaining time resumes.
    init();
  }

  // Expose for the navbar button.
  window.relock = relock;

  document.addEventListener('DOMContentLoaded', function () {
    var btn = document.getElementById('relockBtn');
    if (btn) btn.addEventListener('click', relock);
  });
})(window, document);
